print(float(10))
print(float(10))
print(float(True))
print(float("20"))
print(float("20.5"))
#print(float("bala"))
print(bool(0))
print(bool(0.0))
print(bool(5))
print(bool(0.5))
print(bool(2.5))
print(bool(" "))
print(bool("hi"))
print(bool(False))
print(bool(True))
